name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest yamllint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Yaml Lint
        run: |
          yamllint -d relaxed --no-warnings .
      - name: Test with pytest
        run: |
          pytest upgrade_fw.py

  package:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Create a Debian package
        run: |
          sudo apt install python3-setuptools python3-stdeb dh-python python3-all
          python3 setup.py sdist
          py2dsc --with-python3=true dist/upgrade-fw-1.0.0.tar.gz
          cd deb_dist/upgrade-fw-1.0.0
          dpkg-buildpackage -rfakeroot -uc -us

